import Head from "next/head"
import About_Block from "../components/About";
import Footer from "../components/footer";
import Navbar from "../components/navbar";
import Showcase from "../components/showcase";


const About = () => {
  return (
    <>
      <Head>
        <title>Project About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-auto min-h-[100vh] flex flex-col bg-primary">
        <Navbar />
        <main className="w-full h-auto  mt-20 md:mt-20 flex flex-col items-center justify-center">
          <Showcase remove/>
            <About_Block />
          <Footer />
        </main>
      </div>
    </>
  )
}

export default About