import Footer from "../components/footer";
import Head from "next/head";
import Image from "next/image";
import ImageUploader from "../components/ImageUploader";
import Link from "next/link";
import Navbar from "../components/navbar";
import { UPLOAD_IMAGE } from "../utils";
import { motion } from "framer-motion";
import { toast } from "react-toastify";
import { useRouter } from "next/router";
import { useState } from "react";
import { useStateValue } from "../context/stateProvider";

const ChequeUpload = () => {
  const router = useRouter();
  const [{}, dispatch] = useStateValue();

  const data = [
    {
      title: "Cheque_1",
      image: require("../public/assets/cheque.png"),
    },
    {
      title: "Cheque_2",
      image: require("../public/assets/cheque.png"),
    },
    {
      title: "Cheque_3",
      image: require("../public/assets/cheque.png"),
    },
    {
      title: "Cheque_4",
      image: require("../public/assets/cheque.png"),
    },
    {
      title: "Cheque_5",
      image: require("../public/assets/cheque.png"),
    },
    {
      title: "Cheque_6",
      image: require("../public/assets/cheque.png"),
    },
  ];

  const Cheque = ({ title, image }: { title: string; image: any }) => {
    return (
      <div className="space-y-2 h-[11rem] md:mr-4 w-[18rem] my-2 border-2 border-[#A5A5A5] rounded-lg shadow-lg flex flex-col items-center justify-center">
        <Image alt="cheque" src={image} className="" />
        <p className="text-black ">{title}</p>
      </div>
    );
  };

  const [image, setImage] = useState<null | any>(null);
  const [imageURI, setImageURI] = useState(null);

  const handleUpload = () => {
    if (!imageURI) return toast.error("Image is required");
    toast.promise(
      UPLOAD_IMAGE(imageURI, (data) => {
        console.log(data);
        data.url = image;
        dispatch({
          type: "SET_CHEQUE",
          playload: data,
        });
        router.push("summary");
      }),
      {
        pending: "Verifying cheque......",
        success: "Cheque verified, Redirecting to cheque summary page"
        
      }
    );
  };
  return (
    <div>
      <Head>
        <title>Upload Cheque</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar bg />

      <div className="px-10">
        <div className="text-black mt-32 w-full flex flex-col items-center justify-center">
          <h1 className="font-bold text-center md:text-start text-[2rem] md:text-[3rem]">
            Upload your Cheque
          </h1>
          <div className="h-[2px] w-20 md:w-48 bg-black"></div>
          <p className="text-[#4C4F55] md:w-[45rem] text-center mt-4">
            JPG, JPEG or PNG formats that are 300 x 300 (for HiDPI Displays) are
            accepted. If your image size is bigger, please compress it.
          </p>
        </div>

        <div className="my-8 mt-12 flex flex-col items-center justify-center">
          <ImageUploader
            setImageURI={setImageURI}
            image={image}
            setImage={setImage}
            className="md:w-[30rem] md:h-[20rem]"
          />
          {/* proceed button */}
      {
        imageURI && (
          <motion.button
          onClick={handleUpload}
          whileHover={{ scale: 1.02 }}
          className="bg-green-600 font-semibold text-white text-lg px-10 py-2 rounded-lg mt-8"
        >
          Verify Cheque
        </motion.button>
        )
      }
        </div>

        <div className="flex flex-col items-center justify-center lg:items-start">
          <div className="items-start mt-6">
            <h2 className="text-black text-[1.6rem]">Recently Uploaded</h2>
            <div className="h-[2px] bg-black w-[5rem] "></div>
          </div>

          <motion.div
            initial={{ opacity: 0, x: 200 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 200 }}
            className="flex flex-wrap mt-6 mb-24 items-center justify-center lg:justify-start"
          >
            {data.map((item, idx) => (
              <Cheque key={idx} title={item.title} image={item.image} />
            ))}
          </motion.div>
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default ChequeUpload;
